FIXUP: FROMLIST: drm/mediatek: add dsi module reset driver
0day reports:

drivers/gpu/drm/mediatek/mtk_dsi.c:1333:24: warning:
	symbol 'mtk_dsi_driver' was not declared. Should it be static?

In file included from drivers/gpu//drm/mediatek/mtk_dsi.c:29:0:
   drivers/gpu//drm/mediatek/mtk_dsi.c: In function 'mtk_dsi_reset_all':
drivers/gpu//drm/mediatek/mtk_dsi.c:303:27: error: large integer
	implicitly truncated to unsigned type [-Werror=overflow]

Fix the first problem by including mtk_drm_drv.h.

Fix the second problem by writing 0 instead of "~MMSYS_SW_RST_DSI_B".
Since the mask is MMSYS_SW_RST_DSI_B, writing 0 has the same result
as writing "~MMSYS_SW_RST_DSI_B".

BUG=b:129586227
TEST=Build with C=1 (smatch)

Change-Id: I89d8852325e78029653745d7a1a6809528ba0989
Reported-by: kbuild test robot <lkp@intel.com>
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1647543
Legacy-Commit-Queue: Commit Bot <commit-bot@chromium.org>
Reviewed-by: Hsin-Yi Wang <hsinyi@chromium.org>