FIXUP: FROMLIST: devfreq: add mediatek cci devfreq
0day reports:

drivers//devfreq/mt8183-cci-devfreq.c: In function 'mtk_cci_devfreq_probe':
drivers//devfreq/mt8183-cci-devfreq.c:175:20: warning:
		too many arguments for format [-Wformat-extra-args]
	dev_err(cci_dev, "cannot create cci devfreq device\n", ret);

It does have a point.

In addition to fixing the warning, ret needs to be set to a value != 0.
Otherwise the function will return no error even after an error was
observed.

BUG=b:129039370
TEST=build without build warning

Change-Id: I026a4bc48aea724bea1a850e8b1b2bf9e3ff4638
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1557214
Reviewed-by: Nicolas Boichat <drinkcat@chromium.org>