FIXUP: FROMLIST: platform: mtk-isp: Add Mediatek DIP driver (RFC V3)
0-day reports:

ERROR: "__udivdi3" [drivers/media/platform/mtk-isp/isp_50/dip/mtk_dip.ko] undefined!
ERROR: "__divdi3" [drivers/media/platform/mtk-isp/isp_50/dip/mtk_dip.ko] undefined!

Also:

drivers/media/platform/mtk-isp/isp_50/dip/mtk_dip-sys.c:42:4: warning:
	format '%ld' expects argument of type 'long int', but argument 3 has type 'int'
drivers/media/platform/mtk-isp/isp_50/dip/mtk_dip-sys.c:273:9: warning:
	format '%d' expects a matching 'int' argument

TEST=Build on 32-bit system passes
TEST=Build pass without warnings
BUG=b:140012892, b:111289971

Change-Id: I498e3371d8802f494ad40a89933e5819a6787004
Reported-by: kbuild test robot <lkp@intel.com>
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/1810193
Reviewed-by: Tomasz Figa <tfiga@chromium.org>