CHROMIUM: amdgpu/gmc: fix compile warnings/errors
drivers/gpu/drm/amd/amdgpu/gmc_v8_0.c:
	In function ‘gmc_v8_0_process_interrupt’:
drivers/gpu/drm/amd/amdgpu/gmc_v8_0.c:1447:10:
	error: missing braces around initializer

and similar errors.

Also see:
  https://lore.kernel.org/patchwork/patch/985843/
  https://lkml.kernel.org/r/1536919552-116245-1-git-send-email-peng.hao2@zte.com.cn

The suggested patch was rejected and is incomplete. Rejection is odd because there
are around 50 instances with the same initialization pattern in amd gpu code,
but that is life. For the time being, carry our own fix.

BUG=chromium:885330
TEST=Build AMD image

Change-Id: I93cd1ed7198db9d125131ba58071ee6c3f89fb51
Signed-off-by: Guenter Roeck <groeck@chromium.org>