FIXUP: BACKPORT: media: v4l2-mem2mem: Rename v4l2_m2m_buf_copy_data to v4l2_m2m_buf_copy_metadata
Building with "make allyesconfig" for x86_64 gives the following build
error:

drivers/media/platform/vim2m.c: In function device_process:
drivers/media/platform/vim2m.c:244:2: error: implicit declaration of function v4l2_m2m_buf_copy_data; did you mean v4l2_m2m_buf_copy_metadata? [-Werror=implicit-function-declaration]
  v4l2_m2m_buf_copy_data(in_vb, out_vb, true);
  ^~~~~~~~~~~~~~~~~~~~~~
  v4l2_m2m_buf_copy_metadata
cc1: some warnings being treated as errors
scripts/Makefile.build:303: recipe for target 'drivers/media/platform/vim2m.o' failed
make[3]: *** [drivers/media/platform/vim2m.o] Error 1
scripts/Makefile.build:544: recipe for target 'drivers/media/platform' failed
make[2]: *** [drivers/media/platform] Error 2
scripts/Makefile.build:544: recipe for target 'drivers/media' failed
make[1]: *** [drivers/media] Error 2
Makefile:1055: recipe for target 'drivers' failed
make: *** [drivers] Error 2

The difference between the upstream commit and the backport seems to be a
missing rename from "v4l2_m2m_buf_copy_data" to "v4l2_m2m_buf_copy_metadata"
when backporting
   a4d3d61254d3 ("media: v4l2-mem2mem: Rename v4l2_m2m_buf_copy_data to v4l2_m2m_buf_copy_metadata")

BUG=chromium:966885,b:123551776
TEST=make allyesconfig, make allmodconfig, tryjobs

Change-Id: I46e9c237c42944b014d047a96b0a9e9b0f46c4c0
Reviewed-on: https://chromium-review.googlesource.com/1627559
Commit-Ready: Zubin Mithra <zsm@chromium.org>
Tested-by: Zubin Mithra <zsm@chromium.org>
Legacy-Commit-Queue: Commit Bot <commit-bot@chromium.org>
Reviewed-by: Alexandre Courbot <acourbot@chromium.org>
Reviewed-by: Matthias Kaehlcke <mka@chromium.org>