UPSTREAM: soc: qcom: smp2p: Add select IRQ_DOMAIN
Since we are using irq_domain_add_linear(), add a select on IRQ_DOMAIN.
This is needed in order to be able to remove the depends on ARCH_QCOM.

drivers/soc/qcom/smp2p.c: In function qcom_smp2p_inbound_entry:
drivers/soc/qcom/smp2p.c:317:18: error: implicit declaration of function
  irq_domain_add_linear
  entry->domain = irq_domain_add_linear(node, 32, &smp2p_irq_ops, entry);
                  ^~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Niklas Cassel <niklas.cassel@linaro.org>
Reviewed-by: Vivek Gautam <vivek.gautam@codeaurora.org>
Reviewed-by: Vinod Koul <vkoul@kernel.org>
Signed-off-by: Andy Gross <andy.gross@linaro.org>
(cherry picked from commit 810f11a9cbfda027252d23a4a52d4af814296129)

BUG=none
TEST=build for cheza

Change-Id: I863a79e29d2b9ce0bf52f4f211b0747dfd9763df
Signed-off-by: Matthias Kaehlcke <mka@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1309147
Reviewed-by: Evan Green <evgreen@chromium.org>