FIXUP: CHROMIUM: drm/mediatek: add display debug patch
drivers/gpu/drm/mediatek/mtk_drm_debug.c:
	In function ‘mtk_drm_dbg_dump_comp_reg’:
./include/linux/kern_levels.h:5:18: warning:
	format ‘%lX’ expects argument of type ‘long unsigned int’,
	but argument 2 has type ‘u32 {aka unsigned int}’

drivers/gpu/drm/mediatek/mtk_drm_debug.c: In function ‘mtk_drm_dbg_init’:
./include/linux/kern_levels.h:5:18: warning: too many arguments for format

Also, the code in mtk_drm_dbg_init() suggests that at least theoretically
dev->of_node could be NULL. Add check before dereferencing.

BUG=b:169734618
TEST=Build without warning; boot kukui

Change-Id: I514c78b421c36d0266cd30cadf5a56187f9f3db6
Disallow-Recycled-Builds: test-failures
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/2704034
Reviewed-by: Stéphane Marchesin <marcheu@chromium.org>