Revert "CHROMIUM: hardlockup: detect hard lockups without NMIs using secondary cpus"
This reverts commit 1466322e07575c51f2af67a6616e8a983c0c7678.

This patch breaks almost all test builds.

Example: arm64:defconfig:

panic.c:(.text+0xd4): undefined reference to `arch_touch_nmi_watchdog'
panic.c:(.text+0xd4): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol `arch_touch_nmi_watchdog'
panic.c:(.text+0x164): undefined reference to `arch_touch_nmi_watchdog'
panic.c:(.text+0x164): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol `arch_touch_nmi_watchdog'

BUG=chromium:941638
TEST=arm64:defconfig, and many others

Change-Id: Id0891ab97670073d57412a82d471c0dc59ff2d65
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/1662070
Reviewed-by: Douglas Anderson <dianders@chromium.org>
Reviewed-by: Matthias Kaehlcke <mka@chromium.org>