FIXUP: FROMLIST: sched/core: Update core scheduler queue when taking cpu online/offline
Fix more problems reported by 0-day.

kernel/sched/core.c:6813:29: error:
		use of undeclared identifier 'CPU_ACTIVATE
kernel/sched/core.c:6865:29: error:
		use of undeclared identifier 'CPU_DEACTIVATE'

Also fix follow-up warning that sched_core_enqueued() may be unused.

BUG=b:152605392
TEST=Test builds

Change-Id: I3c25bae0dd1bcdd2c94c050915a167622641468f
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/2250162
Reviewed-by: Joel Fernandes <joelaf@google.com>