FIXUP: CHROMIUM: devfreq: rockchip: Add clk-rk3288-dmc driver
arm64:allmodconfig fails to build.

drivers/devfreq/rockchip/clk-rk3288-dmc.c:11:10: fatal error:
	asm/idmap.h: No such file or directory

The driver depends on CONFIG_ARM.

BUG=chromium:941638
TEST=Build arm64:allmodconfig

Change-Id: Ieaf1611ca5467082e300b130768956311156b4ae
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1591589
Reviewed-by: Douglas Anderson <dianders@chromium.org>