UPSTREAM: soc: qcom: smem: Add missing include of sizes.h
Add missing include of sizes.h.

drivers/soc/qcom/smem.c: In function qcom_smem_get_ptable:
drivers/soc/qcom/smem.c:666:64: error: SZ_4K undeclared
  ptable = smem->regions[0].virt_base + smem->regions[0].size - SZ_4K;
                                                                ^~~~~

Signed-off-by: Niklas Cassel <niklas.cassel@linaro.org>
Reviewed-by: Vivek Gautam <vivek.gautam@codeaurora.org>
Reviewed-by: Vinod Koul <vkoul@kernel.org>
Signed-off-by: Andy Gross <andy.gross@linaro.org>
(cherry picked from commit 9487e2ab1010c92789471d944230ecd38c720333)

BUG=none
TEST=build for cheza

Change-Id: I361d4282e09177b51fa4ea9365d3592f4063c9e1
Signed-off-by: Matthias Kaehlcke <mka@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1309145
Reviewed-by: Evan Green <evgreen@chromium.org>