Revert "CHROMIUM: config: arm{32,64}: panic when a hardlockup is detected"
This reverts commit a2e6f608234aa43e56092a80923f4797bb0023ef.

This patch breaks almost all test builds.

Example: arm64:defconfig:

panic.c:(.text+0xd4): undefined reference to `arch_touch_nmi_watchdog'
panic.c:(.text+0xd4): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol `arch_touch_nmi_watchdog'
panic.c:(.text+0x164): undefined reference to `arch_touch_nmi_watchdog'
panic.c:(.text+0x164): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol `arch_touch_nmi_watchdog'

BUG=chromium:941638
TEST=arm64:defconfig, and many others

Change-Id: I6fc929350d6ee441858892c61ae993f07a6c69f2
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/1662069
Reviewed-by: Douglas Anderson <dianders@chromium.org>