FIXUP: FROMLIST: mfd: Add support for the MediaTek MT6358 PMIC
This patch also fixes commit 08806d8a7bc7 ("FROMLIST: mfd: mt6397:
extract irq related code from core driver").

Building the mt6397/mt6358 driver as module results in the following
errors.

ERROR: "mt6397_irq_init" [drivers/mfd/mt6397-core.ko] undefined!
ERROR: "mt6358_irq_init" [drivers/mfd/mt6397-core.ko] undefined!

This is because the irq code for mt6358 and mt6397_irq is built
as separate modules, but the functions implemented by those modules
are not exported. We could export the functions, but that seems to
be quite pointless since the driver always requires both interrupt
handlers. Modify the Makefile to build a single module instead.

BUG=b:126006378
TEST=build mt6397/mt6358 driver as module

Signed-off-by: Guenter Roeck <groeck@chromium.org>

Change-Id: I1ec4a41f6006ef56790e4bfd2f4d0d16240e8f80
Reviewed-on: https://chromium-review.googlesource.com/1524423
Commit-Ready: Guenter Roeck <groeck@chromium.org>
Tested-by: Guenter Roeck <groeck@chromium.org>
Reviewed-by: Nicolas Boichat <drinkcat@chromium.org>