FIXUP: FROMLIST: drm/mediatek: change the dsi phytiming calculate method
Building the driver fails with

ERROR: "__aeabi_uldivmod" [drivers/gpu/drm/mediatek/mediatek-drm.ko] undefined!

when building 32-bit images. The problem is caused by the data_rate
variable in in struct mtk_dsi, which is declared as u64. It is calculated
as
	dsi->data_rate = dsi->vm.pixelclock * bit_per_pixel / dsi->lanes;
None of the parameters are u64, resulting in an overflow if the result or
even dsi->vm.pixelclock * bit_per_pixel is larger than unsigned long. On
top of that, data_rate is then used as parameter to clk_set_rate(), which
expects an unsigned long parameter. Thus, there is no value declaring
data_rate as u64. Declare it as unsigned long instead.

Also use div_u64() to calculate cycle_time to avoid another 64-bit divide
operation.

BUG=b:129586227
TEST=boot to welcome screen

Change-Id: I130ce7baeddf68da25f2134bac73ae6d0c23924f
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1639756
Legacy-Commit-Queue: Commit Bot <commit-bot@chromium.org>
Reviewed-by: Nicolas Boichat <drinkcat@chromium.org>
Reviewed-by: Ryan Case <ryandcase@chromium.org>