FIXUP: FROMLIST: drm/bridge: add it6505 driver (take two)
More 0day reports.

drivers/gpu/drm/bridge/ite-it6505.c:2519:3-8:
	No need to set .owner here. The core will do it.

Several more instances of C compiler warnings such as the following.

drivers/gpu/drm/bridge/ite-it6505.c:1874:28: error:
	field width specifier '*' expects argument of type 'int',
	but argument 4 has type 'long unsigned int'

aclk can be uninitialized in it6505_intp_threaded_handler().

BUG=b:126007406
TEST=Compile and observe warnings

Change-Id: Iee874ef0e49b53a5a46e0dc6aef79ac48018257a
Reported-by: kbuild test robot <lkp@intel.com>
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/1793127
Reviewed-by: Nicolas Boichat <drinkcat@chromium.org>
Commit-Queue: Nicolas Boichat <drinkcat@chromium.org>
Tested-by: Nicolas Boichat <drinkcat@chromium.org>