mm: swap: Remove use case of `lru` & `LRU_ACTIVE`
ACK gerrit doesn't have page_lru_base_type() declared.
Assigning lru as an int type to an undeclared function
will just cause an implicit declaration.

lru is not even assigned as an enum at del_page_from_lru_list()
anyway, get rid of it and honor ACK's changes.

ChromeOS stopped passing enum lru_list anyway [1].
Additionally, honor ChromeOS kernel's changes and remove
LRU_ACTIVE.

This fixes the following compilation errors:

../mm/swap.c:591:13: error: implicit declaration of function 'page_lru_base_type' [-Werror,-Wimplicit-function-declaration]
                int lru = page_lru_base_type(page);
                          ^
../mm/swap.c:593:40: error: too many arguments to function call, expected 2, have 3
                del_page_from_lru_list(page, lruvec, lru + LRU_ACTIVE);
                ~~~~~~~~~~~~~~~~~~~~~~               ^~~~~~~~~~~~~~~~
../include/linux/mm_inline.h:311:29: note: 'del_page_from_lru_list' declared here
static __always_inline void del_page_from_lru_list(struct page *page,
                            ^
../mm/swap.c:596:38: error: too many arguments to function call, expected 2, have 3
                add_page_to_lru_list(page, lruvec, lru);
                ~~~~~~~~~~~~~~~~~~~~               ^~~
../include/linux/mm_inline.h:287:29: note: 'add_page_to_lru_list' declared here
static __always_inline void add_page_to_lru_list(struct page *page,
                            ^

[1]: https://github.com/Atom-X-Devs/android_kernel_xiaomi_scarlet/commit/5f5a2bc6350a652f4610c44fb2f6f80081d888cf

Signed-off-by: Tashfin Shakeer Rhythm <tashfinshakeerrhythm@gmail.com>