FIXUP: UPSTREAM: drm/bridge: add support for sn65dsi86 bridge driver
0day reports:

   drivers/gpu/drm/bridge/ti-sn65dsi86.o: In function `ti_sn_bridge_remove':
>> drivers/gpu/drm/bridge/ti-sn65dsi86.c:629: undefined reference to `mipi_dsi_detach'
>> drivers/gpu/drm/bridge/ti-sn65dsi86.c:630: undefined reference to `mipi_dsi_device_unregister'
   drivers/gpu/drm/bridge/ti-sn65dsi86.o: In function `ti_sn_bridge_attach':
>> drivers/gpu/drm/bridge/ti-sn65dsi86.c:249: undefined reference to `of_find_mipi_dsi_host_by_node'
>> drivers/gpu/drm/bridge/ti-sn65dsi86.c:256: undefined reference to `mipi_dsi_device_register_full'
>> drivers/gpu/drm/bridge/ti-sn65dsi86.c:276: undefined reference to `mipi_dsi_attach'
   drivers/gpu/drm/bridge/ti-sn65dsi86.c:289: undefined reference to `mipi_dsi_device_unregister'

Quite obviously the driver depends on DRM_MIPI_DSI.
We can not use "depends" since the driver configuration uses "select",
so we'll have to select the missing dependency instead.

Change-Id: I70bbabf6bae97ca223bf0003434765d7f72a66f5
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1176224
Reviewed-by: Sean Paul <seanpaul@chromium.org>