char: srandom: Remove redundant stack guard
We already have stack protector guarding the stack within
its macro check. Using another declaration here causes
symbols to be duplicated which causes compilation error.
This is not even called from anywhere within srandom.
Therefore, we can drop this.

This fixes the following compilation errors:

ld.lld: error: duplicate symbol: __stack_chk_guard
>>> defined at process.c
>>>            process.o:(__stack_chk_guard) in archive arch/arm64/kernel/built-in.a
>>> defined at srandom.c
>>>            char/srandom.o:(.bss+0xF0) in archive drivers/built-in.a

ld.lld: error: duplicate symbol: __stack_chk_fail
>>> defined at panic.c
>>>            panic.o:(__stack_chk_fail) in archive kernel/built-in.a
>>> defined at srandom.c
>>>            char/srandom.o:(.text+0xE00) in archive drivers/built-in.a

Fixes: 94339bf77a ("char: srandom: Upgrade to upstream version 1.40.0")
Signed-off-by: Tashfin Shakeer Rhythm <tashfinshakeerrhythm@gmail.com>