FIXUP: CHROMIUM: Device driver for TPM over virtio
0day reports:

ld: drivers/char/tpm/tpm_virtio.o: in function `vtpm_wait_for_buffer':
>> drivers/char/tpm/tpm_virtio.c:115: undefined reference to `virtqueue_kick'
>> ld: drivers/char/tpm/tpm_virtio.c:166: undefined reference to `virtqueue_get_buf'
   ld: drivers/char/tpm/tpm_virtio.o: in function `vtpm_op_send':
>> drivers/char/tpm/tpm_virtio.c:238: undefined reference to `virtqueue_add_sgs'
>> ld: drivers/char/tpm/tpm_virtio.c:245: undefined reference to `virtqueue_kick'
   ld: drivers/char/tpm/tpm_virtio.o: in function `vtpm_driver_init':
>> drivers/char/tpm/tpm_virtio.c:458: undefined reference to `register_virtio_driver'
   ld: drivers/char/tpm/tpm_virtio.o: in function `vtpm_driver_exit':
>> drivers/char/tpm/tpm_virtio.c:458: undefined reference to `unregister_virtio_driver'

Quite obviously the driver depends on VIRTIO.

BUG=chromium:911799
TEST=Test builds

Change-Id: I2d921b9a30a8b5061a40905a00a17752aa64e305
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1500115
Reviewed-by: David Tolnay <dtolnay@chromium.org>
Reviewed-by: Dylan Reid <dgreid@chromium.org>