FIXUP: CHROMIUM: [media] hantro: add VP8 encoding support (take 2)
0day reports:

drivers/staging/media/hantro/hantro.h:330:4: note:
	in expansion of macro 'pr_info'
drivers/staging/media/hantro/hantro_h1_vp8_enc.c:154:2: note:
	in expansion of macro 'vpu_debug'
include/linux/bits.h:6:19: error:
	large integer implicitly truncated to unsigned type
include/linux/kern_levels.h:5:18: warning:
	format '%u' expects argument of type 'unsigned int',
	but argument 5 has type 'size_t {aka long unsigned int}' [-Wformat=]

BUG=chromium:965378
TEST=tast video.EncodeAccel* on veyron-minnie-kernelnext

Change-Id: I7b7e38fd3594be77374314692c1d7d7cb3a0c012
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/1804218
Reviewed-by: Douglas Anderson <dianders@chromium.org>