FIXUP: BACKPORT: drm/i915: Add HDCP 1.4 support for MST connectors
0-day says:

drivers/gpu/drm/i915/intel_dp_hdcp.c:
	In function 'intel_dp_mst_hdcp_toggle_signalling':
drivers/gpu/drm/i915/intel_dp_hdcp.c:247:27: error:
	unused variable 'i915'

The backport replaced drm_dbg_kms with DRM_DEBUG_KMS. As result,
the offending variable is no longer used in two functions.

BUG=b:156333982
TEST=Compile

Change-Id: Ia71fc375d2700c41aff84de46938cf322fd35dda
Disallow-Recycled-Builds: test-failures
Reported-by: kernel test robot <lkp@intel.com>
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/2537392
Reviewed-by: Sam McNally <sammc@chromium.org>
Reviewed-by: Edward O'Callaghan <quasisec@chromium.org>