FIXUP: BACKPORT: FROMLIST: platform: mtk-isp: Add Mediatek FD driver (take 2)
0day now reports:

drivers/media/platform/mtk-isp/fd/mtk_fd_40.c:258:17: error:
	format '%d' expects argument of type 'int',
	but argument 4 has type 'long unsigned int'

Guess I should test my own fixes.

BUG=b:140012409
TEST=build pass

Signed-off-by: Guenter Roeck <groeck@chromium.org>
Change-Id: I0e5e751e1ba0725f373cbb07d63350baf11e3770
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/1800514
Commit-Queue: Nicolas Boichat <drinkcat@chromium.org>
Reviewed-by: Nicolas Boichat <drinkcat@chromium.org>
Tested-by: Nicolas Boichat <drinkcat@chromium.org>