Revert "FROMLIST: i2c: mediatek: disable zero-length transfers for mt8183"
This reverts commit c4d886665235b2f31f8aaba9cf58bc0c1d866f0c.

Reason for revert: Refresh to FROMGIT version

Original change's description:
> FROMLIST: i2c: mediatek: disable zero-length transfers for mt8183
>
> When doing i2cdetect quick write mode, we would get transfer
> error ENOMEM, and i2cdetect shows there's no device at the address.
> Quoting from mt8183 datasheet, the number of transfers to be
> transferred in one transaction should be set to bigger than 1,
> so we should forbid zero-length transfer and update functionality.
>
> Incorrect return:
> localhost ~ # i2cdetect -q -y 0
>      0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
> 00:          -- -- -- -- -- -- -- -- -- -- -- -- --
> 10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
> 20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
> 30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
> 40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
> 50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
> 60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
> 70: -- -- -- -- -- -- -- --
>
> After this patch:
> localhost ~ #  i2cdetect -q -y 0
> Error: Can't use SMBus Quick Write command on this bus
>
> localhost ~ #  i2cdetect -y 0
> Warning: Can't use SMBus Quick Write command, will skip some addresses
>      0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
> 00:
> 10:
> 20:
> 30: -- -- -- -- -- -- -- --
> 40:
> 50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
> 60:
> 70:
>
> Reported-by: Alexandru M Stan <amstan@chromium.org>
> Signed-off-by: Hsin-Yi Wang <hsinyi@chromium.org>
>
> (am from https://patchwork.ozlabs.org/patch/1137315/)
>
> TEST=`i2cdetect -y BUSNUM`
> BUG=b:138354308
>
> Change-Id: I36607f287ffe4d7c5d90bc2edcfe8a0dce3122bd
> Signed-off-by: Hsin-Yi Wang <hsinyi@chromium.org>
> Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/1496704
> Reviewed-by: Sean Paul <seanpaul@chromium.org>
> Reviewed-by: Nicolas Boichat <drinkcat@chromium.org>
> Reviewed-by: Alexandru M Stan <amstan@chromium.org>

Bug: b:138354308
Change-Id: I9540d13ebd75bb0d73c18a6abeae92c537d39c9d
Cq-Depend: chromium:1781262
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/1781261
Commit-Queue: Hsin-Yi Wang <hsinyi@chromium.org>
Tested-by: Hsin-Yi Wang <hsinyi@chromium.org>
Reviewed-by: Hsin-Yi Wang <hsinyi@chromium.org>
Reviewed-by: Nicolas Boichat <drinkcat@chromium.org>