FROMGIT: ASoC: Mediatek: MT8183: Fix build error in mt8183_da7219_max98357_dev_probe
When building CONFIG_SND_SOC_MT8183_DA7219_MAX98357A=m
gcc warn this:

sound/soc/mediatek/mt8183/mt8183-da7219-max98357.c: In function mt8183_da7219_max98357_dev_probe:
sound/soc/mediatek/mt8183/mt8183-da7219-max98357.c:413:13: error: struct snd_soc_dai_link has no member named platform; did you mean platforms?
   dai_link->platform = NULL;
             ^~~~~~~~
             platforms

use 'dai_link->platforms' instead of 'dai_link->platform'.

Fixes: 11c0269017b2 ("ASoC: Mediatek: MT8183: Add machine driver with TS3A227")
Signed-off-by: YueHaibing <yuehaibing@huawei.com>
Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 52a30f3bb1b15c7d27233e9947370c1c14b5cbae
 https://git.kernel.org/pub/scm/linux/kernel/git/broonie/sound.git
 for-next))

BUG=b:124717947,b:129043735
TEST=build and boot to shell

Change-Id: I80b935860fc6d78e4f88fb3c0952e97591be205b
Signed-off-by: Eddie Huang <eddie.huang@mediatek.com>
Reviewed-on: https://chromium-review.googlesource.com/1556978
Reviewed-by: Tzung-Bi Shih <tzungbi@chromium.org>
Reviewed-by: Nicolas Boichat <drinkcat@chromium.org>