FIXUP: CHROMIUM: sched: Add a per-thread core scheduling interface
0-day reports:

kernel/sched/core.c: In function 'task_set_core_sched':
kernel/sched/core.c:7117:46: error:
		'struct task_struct' has no member named 'sched_task_group'

Apparently SCHED_CORE depends on CGROUP_SCHED. Add dependency and rearrange
code to avoid follow-up errors.

BUG=b:152605392
TEST=test builds

Change-Id: I634bf322ad96a77df614ddf57b4d8e11c04372f7
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/2248700
Reviewed-by: Joel Fernandes <joelaf@google.com>