sultan_bench: Add missing scheduling parameter header
This fixes the following compilation errors:

../kernel/sultan_bench.c:168:34: error: variable has incomplete type 'const struct sched_param'
        static const struct sched_param sched_max_rt_prio = {
                                        ^
../include/linux/sched.h:53:8: note: forward declaration of 'struct sched_param'
struct sched_param;
       ^
../kernel/sultan_bench.c:222:34: error: variable has incomplete type 'const struct sched_param'
        static const struct sched_param sched_max_rt_prio = {
                                        ^
../include/linux/sched.h:53:8: note: forward declaration of 'struct sched_param'
struct sched_param;
       ^

Signed-off-by: Tashfin Shakeer Rhythm <tashfinshakeerrhythm@gmail.com>