FIXUP: CHROMIUM: drm/virtgpu: check for revelant capabilites
Test builds report:

drivers/gpu/drm/virtio/virtgpu_kms.c: In function 'virtio_gpu_init':
drivers/gpu/drm/virtio/virtgpu_kms.c:168:10: error:
	implicit declaration of function 'pci_request_region';
	did you mean 'pci_request_regions'?

Per coding style, any source file using an external function shall include
the file declaring it. Also, since the missing function is called
uncoditionally, the driver now depends on PCI. This is even more the case
since the driver now dereferences dev->pdev unconditionally under some
conditions, meaning the code might crash if the underlying device is not
a PCI device.

[ Why wasn't the offending patch sent upstream ? And why do we introduce
  dependencies on PCI is this code ? ]

BUG=chromium:924405
TEST=compile

Change-Id: I8ea30179acdec9dc5e00e5bfddf6a2216954d268
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/1827071
Reviewed-by: Gurchetan Singh <gurchetansingh@chromium.org>