FIXUP: BACKPORT: FROMLIST: platform: mtk-isp: Add Mediatek FD driver
0day reports:

divers/media/platform/mtk-isp/fd/mtk_fd_40.c:258:17: error:
	format '%d' expects a matching 'int' argument
drivers/media/platform/mtk-isp/fd/mtk_fd_40.c:269:17: error:
	too many arguments for format
drivers/media/platform/mtk-isp/fd/mtk_fd_40.c:274:17: error:
	format '%d' expects a matching 'int' argument

0day further reports:

./usr/include/linux/mtk-fd-v4l2-controls.h:21:
	found __[us]{8,16,32,64} type without #include <linux/types.h>

When configuring a system without ARCH_MEDIATEK support,
we also get:

WARNING: unmet direct dependencies detected for MTK_SCP

which is again caused by an unconditional "select MTK_SCP".

BUG=b:140012409
TEST=build pass

Change-Id: Ic2f93fe4d8d2beb6fcb057d601743fc29254cbb0
Reported-by: kbuild test robot <lkp@intel.com>
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/1798389
Commit-Queue: Nicolas Boichat <drinkcat@chromium.org>
Reviewed-by: Nicolas Boichat <drinkcat@chromium.org>
Tested-by: Nicolas Boichat <drinkcat@chromium.org>