FIXUP: FROMLIST: media: platform: mtk-mdp3: Add Mediatek MDP3 driver
0-day reports:

drivers/media/platform/mtk-mdp3/mtk-mdp3-vpu.c:
	In function 'mdp_vpu_dev_init':
drivers/media/platform/mtk-mdp3/mtk-mdp3-vpu.c:182:4: error:
	format '%llx' expects argument of type 'long long unsigned int',
	but argument 5 has type 'size_t'

drivers/media/platform/mtk-mdp3/mtk-mdp3-core.c:
	In function 'mdp_pm_suspend':
include/linux/kern_levels.h:5:18: error:
	format '%d' expects a matching 'int' argument

and many other similar errors/warnings.

0-day also reports an unterminated of_device_id table.

Also:

ERROR: "__aeabi_ldivmod" [drivers/media/platform/mtk-mdp3/mtk-mdp3.ko] undefined!
ERROR: "__aeabi_uldivmod" [drivers/media/platform/mtk-mdp3/mtk-mdp3.ko] undefined!

BUG=b:140012896, b:111289971
TEST=build without compiler warnings or errors

Change-Id: I8bfc0a54427b8d7967f79e961254269c6917be77
Reported-by: kbuild test robot <lkp@intel.com>
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/1810192
Reviewed-by: Alexandre Courbot <acourbot@chromium.org>
Tested-by: Alexandre Courbot <acourbot@chromium.org>