sched/fair: Remove `cpu` argument from fits_capacity() macro invocation
fits_capacity() lacks the "cpu" argument in its macro. Hence using it
with an extra non-existent third argument breaks compilation. Remove
the unneeded `cpu` argument.

This fixes the following compilation errors:

../kernel/sched/fair.c:6720:41: error: too many arguments provided to function-like macro invocation
                if (fits_capacity(task_util, cpu_cap, cpu))
                                                      ^
../kernel/sched/fair.c:128:9: note: macro 'fits_capacity' defined here
        ^
../kernel/sched/fair.c:6720:7: error: use of undeclared identifier 'fits_capacity'
                if (fits_capacity(task_util, cpu_cap, cpu))
                    ^

Signed-off-by: Tashfin Shakeer Rhythm <tashfinshakeerrhythm@gmail.com>