FROMGIT: ASoC: Mediatek: MT8183: TS3A227: fix build error
When building CONFIG_SND_SOC_MT8183_MT6358_TS3A227E_MAX98357A=m the
following error pops up:

../sound/soc/mediatek/mt8183/mt8183-mt6358-ts3a227-max98357.c: In function mt8183_mt6358_ts3a227_max98357_dev_probe:
../sound/soc/mediatek/mt8183/mt8183-mt6358-ts3a227-max98357.c:325:13: error: struct snd_soc_dai_link has no member named platform; did you mean platforms?
   dai_link->platform = NULL;
             ^~~~~~~~
             platforms

Rework to use 'dai_link->platforms' instead of 'dai_link->platform'.

Fixes: 11c0269017b2 ("ASoC: Mediatek: MT8183: Add machine driver with TS3A227")
Signed-off-by: Anders Roxell <anders.roxell@linaro.org>
Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 2b7bcdad3af9fbd104d5f300dbb90f684c36aa09
 https://git.kernel.org/pub/scm/linux/kernel/git/broonie/sound.git
 for-next)

BUG=b:129043735
TEST=build and boot to shell

Change-Id: I101e0eabfcf61669e7d2a82a88172dc07c605908
Signed-off-by: Eddie Huang <eddie.huang@mediatek.com>
Reviewed-on: https://chromium-review.googlesource.com/1556977
Reviewed-by: Tzung-Bi Shih <tzungbi@chromium.org>
Reviewed-by: Nicolas Boichat <drinkcat@chromium.org>