UPSTREAM: soc: qcom: llcc-slice: Add missing include of sizes.h
Add missing include of sizes.h.

drivers/soc/qcom/llcc-slice.c: In function llcc_update_act_ctrl:
drivers/soc/qcom/llcc-slice.c:41:44: error: SZ_4K undeclared
 #define LLCC_TRP_ACT_CTRLn(n)         (n * SZ_4K)
                                            ^~~~~

Signed-off-by: Niklas Cassel <niklas.cassel@linaro.org>
Reviewed-by: Vivek Gautam <vivek.gautam@codeaurora.org>
Reviewed-by: Vinod Koul <vkoul@kernel.org>
Signed-off-by: Andy Gross <andy.gross@linaro.org>
(cherry picked from commit da8eaf9a6cee12a0a77c82ffb0c93818e050f0d7)

BUG=none
TEST=build for cheza

Change-Id: Ib4d45e6decadb8fac83d8faadc2a80a1b3cdfcda
Signed-off-by: Matthias Kaehlcke <mka@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1309146
Reviewed-by: Evan Green <evgreen@chromium.org>