UPSTREAM: drm/msm: avoid unused function warning
drivers/gpu/drm/msm/disp/dpu1/dpu_plane.c:368:13: error: 'dpu_plane_danger_signal_ctrl' defined but not used [-Werror=unused-function]

Fixes: 7b2e7adea732 ("drm/msm/dpu: Make dpu_plane_danger_signal_ctrl void")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Anders Roxell <anders.roxell@linaro.org>
Signed-off-by: Rob Clark <robdclark@gmail.com>
(cherry picked from commit a840f690d3c6f2f27425ca7e7bd2d635cdec07d7)

BUG=None
TEST=Tested on cheza, boots and display comes up

Signed-off-by: Sean Paul <seanpaul@chromium.org>
Change-Id: Id6a7ea285e341eee70c18a1e2f1737ffb8c0bb80
Reviewed-on: https://chromium-review.googlesource.com/1439557
Reviewed-by: Stéphane Marchesin <marcheu@chromium.org>