nt36xxx: Replace custom logging macros with pr_*
Dedicated define directives for logging at header is totally unnecessary
when we just can use pr_* to print logs.
NVT_ERR and LOGV weren't even defined at the header, causing compilation
errors. Instead of adding define directives for them, just switch to
simple pr_* logging method. Implement the usage of pr_debug() at touchscreen
driver to get rid of the useless logs.

This also fixes the following compilation errors:

../drivers/input/touchscreen/nt36xxx/nt36xxx.c:1159:3: error: implicit declaration of function 'LOGV' [-Werror,-Wimplicit-function-declaration]
                LOGV("androidboot.mode=charger, TP doesn't support!\n");
                ^
../drivers/input/touchscreen/nt36xxx/nt36xxx.c:1171:4: error: implicit declaration of function 'NVT_ERR' [-Werror,-Wimplicit-function-declaration]
                        NVT_ERR("Touch IC is not nt36672a\n");
                        ^

Signed-off-by: Tashfin Shakeer Rhythm <tashfinshakeerrhythm@gmail.com>