FIXUP: BACKPORT: media: mtk-vcodec: fix build breakage when one of VPU or SCP is enabled
0-day reports:

drivers/media/platform/mtk-vcodec/mtk_vcodec_dec_drv.c: In function 'mtk_vcodec_probe':
drivers/media/platform/mtk-vcodec/mtk_vcodec_dec_drv.c:330:3: error:
	implicit declaration of function 'media_device_init'

drivers/media/platform/mtk-vcodec/mtk_vcodec_dec_drv.c: In function 'mtk_vcodec_dec_remove':
drivers/media/platform/mtk-vcodec/mtk_vcodec_dec_drv.c:409:3: error:
	implicit declaration of function 'media_device_cleanup'

The 'fix build breakage' commit removes "select MEDIA_CONTROLLER".
However, VIDEO_MEDIATEK_VCODEC depends on it thanks to commit
d8b73858258f9 ("BACKPORT: FROMLIST: media: mtk-vcodec: vdec: add
media device if using stateless api"). Adding it back in as "select"
does not work anymore since that creates a dependency recursion.
Add it as dependency instead.

BUG=b:149437087
TEST=tast video.EncodeAccelNew.h264_* passes on Krane
TEST=tast video.EncodeAccelNew.h264_* passes on Hana

Change-Id: I971af627ed0a5e5694329bf0a57285cdf17ec7b3
Disallow-Recycled-Builds: test-failures
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/2710448
Commit-Queue: Tzung-Bi Shih <tzungbi@chromium.org>
Reviewed-by: Alexandre Courbot <acourbot@chromium.org>
Tested-by: Tzung-Bi Shih <tzungbi@chromium.org>