Revert "BACKPORT: media: vicodec: Introducing stateless fwht defs and structs"
This reverts commit a271ba3ecc1f4f5a7cea2ec167a2a76b843b3016.

I have no idea what this backport is about, since CONFIG_VIDEO_VICODEC
isn't enabled in any of our configurations. Either case, it doesn't even
compile with the patch that is being reverted here.

drivers/media/platform/vicodec/vicodec-core.c:63:21: error:
	variable 'pixfmt_fwht' has initializer but incomplete type

A brief glance suggests that context patches such as commit cd12b401adc3c
("media: vicodec: split off v4l2 specific parts for the codec") are
missing. If the patch is indeed needed, it should be backported properly
and at the very least be compile tested.

BUG=chromium:965375
TEST=Build with CONFIG_VIDEO_VICODEC=y

Change-Id: I73c2f32abedaa4320a66fc1fa4a063fcd961cdeb
Reported-by: kbuild test robot <lkp@intel.com>
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/1683897
Commit-Queue: Alexandre Courbot <acourbot@chromium.org>
Reviewed-by: Francois Buergisser <fbuergisser@chromium.org>
Reviewed-by: Alexandre Courbot <acourbot@chromium.org>