CHROMIUM: iio: cros_ec: Spread timestamps better
Sometimes the EC receives only one interrupt (hence timestamp) for
a batch of samples. Only the first sample will have the correct
timestamp. So we must interpolate the other samples.
We use the previous batch timestamp and our current batch timestamp
as a way to calculate period, then spread the samples evenly.

  s0 int, 0ms
  s1 int, 10ms
  s2 int, 20ms
  30ms point goes by, no interrupt, previous one is still asserted
  downloading s2 and s3
  s3 sample, 20ms (incorrect timestamp)
  s4 int, 40ms

The batches are [(s0), (s1), (s2, s3), (s4)]. Since the 3rd batch
has 2 samples in them, we adjust the timestamp of s3.
s2 - s1 = 10ms, so s3 must be s2 + 10ms => 20ms. If s1 would have
been part of a bigger batch things would have gotten a little
more complicated.

BUG=b:73551961, b:67743747, chromium:944342
TEST="help" or "gpioget" on the EC does not cause a blip on the
period graph

(Cherry-picked from 4.4, 4.14)

Change-Id: Ie0dc866bb909144dc20e8e59463abd855add2e75
Signed-off-by: Alexandru M Stan <amstan@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1064477
Reviewed-by: Gwendal Grignou <gwendal@chromium.org>

FIXUP: CHROMIUM: iio: cros_ec: Spread timestamps better

Commit 3af8b8cf09074 ("CHROMIUM: iio: cros_ec: Spread timestamps better") causes
test builds to fail.

drivers/iio/common/cros_ec_sensors/cros_ec_sensors_ring.c:
	In function 'cros_ec_ring_fifo_toggle':
drivers/iio/common/cros_ec_sensors/cros_ec_sensors_ring.c:107:2: error:
	'for' loop initial declarations are only allowed in C99 or C11 mode

Furthermore, there are build warnings.

drivers/iio/common/cros_ec_sensors/cros_ec_sensors_ring.c:
	In function cros_ec_ring_handler:
drivers/iio/common/cros_ec_sensors/cros_ec_sensors_ring.c:352:28: warning:
	format %d expects argument of type int, but argument 6 has type s64 {aka long long int}

BUG=b:73551961, b:67743747
TEST="Build with allmodconfig kernel configurations"

Change-Id: Ib9d64c1c21dafecbda405822339e171a6e992cb9
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1085382
Reviewed-by: Alexandru M Stan <amstan@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1308055
Commit-Ready: ChromeOS CL Exonerator Bot <chromiumos-cl-exonerator@appspot.gserviceaccount.com>
Tested-by: Enrico Granata <egranata@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1533057
Commit-Ready: Alexandru M Stan <amstan@chromium.org>
Tested-by: Alexandru M Stan <amstan@chromium.org>
Reviewed-by: Enrico Granata <egranata@chromium.org>