FIXUP: CHROMIUM: i915: intel_dp_aux_backlight: Fix max backlight calculations
Attempts to build an image with gcc fails as follows.

drivers/gpu/drm/i915/intel_dp_aux_backlight.c:
	In function 'intel_dp_aux_setup_backlight':
drivers/gpu/drm/i915/intel_dp_aux_backlight.c:274:19: error:
	unused variable 'intel_dp'

clang does not care about unused variables, but gcc does, and violently so.

BUG=b:134778235
TEST=Build image with "USE=-clang"

Change-Id: I230c0bbd3a138b3249ce9148927ee0ab3243972b
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/1662628
Reviewed-by: Furquan Shaikh <furquan@chromium.org>