f2fs: Use GC_URGENT_HIGH instead of GC_URGENT
GC_URGENT has been deprecated and replaced with GC_URGENT_HIGH in the
f2fs upstream. Switch to that to fix the following compilation error:

../fs/f2fs/gc.c:85:19: error: use of undeclared identifier 'GC_URGENT'
                        sbi->gc_mode = GC_URGENT;
                                       ^

Signed-off-by: Tashfin Shakeer Rhythm <tashfinshakeerrhythm@gmail.com>