FIXUP: CHROMIUM: img-rogue/1.17: fix more gcc12 warnings
-Werror=designated-init:
  >> drivers/gpu/drm/img-rogue/1.17/physmem_hostmem.c:69:9:         \
    error: positional initialization of field in 'struct' declared  \
    with 'designated_init' attribute [-Werror=designated-init]
     69 |         HostMemCpuPAddrToDevPAddr,
        |

-Wsuggest-attribute=format:
  >> drivers/gpu/drm/img-rogue/1.17/htb_debug.c:113:32:             \
    warning: argument 1 of ‘HTBDumpBuffer’ might be a candidate for \
    a format attribute [-Wsuggest-attribute=format]
    113 |         retVal = HTBDumpBuffer(DIPrintf, psEntry, pvData);
        |

-Wstringop-overread:
  >> drivers/gpu/drm/img-rogue/1.17/rgxta3d.c:600:18:               \
    warning: ‘RIWriteMEMDESCEntryKM’ reading 97 bytes from a region \
    of size 10 [-Wstringop-overread]
    600 |         eError = RIWriteMEMDESCEntryKM(psPMRNode->psPMR,
        |

-Warray-parameter:
  >> drivers/gpu/drm/img-rogue/1.17/ri_server.c:576:52: warning:    \
    argument 3 of type ‘const IMG_CHAR *’ {aka ‘const char *’}      \
    declared as a pointer [-Warray-parameter=]
    576 |         const IMG_CHAR *psz8TextB,

-Wunused-but-set-variable:
  >> drivers/gpu/drm/img-rogue/1.17/pdump_km.h:85:36: warning:      \
    variable ‘here’ set but not used [-Wunused-but-set-variable]
     85 | #define PDUMP_HERE_VAR  IMG_UINT32 here = 0;

-Wmissing-include-dirs:
  cc1: warning: include/drm:                                        \
  No such file or directory [-Wmissing-include-dirs]

BUG=b:248494872
TEST=make --keep-going ARCH=arm64 SHELL=/bin/bash CROSS_COMPILE=\
 ~/0day/gcc-12.1.0-nolibc/aarch64-linux/bin/aarch64-linux- \
 drivers/gpu/drm/img-rogue/1.17/

Change-Id: I500d0b62c506bfda5e79a49e545e2eea6f8c4708
Signed-off-by: Luigi Santivetti <luigi.santivetti@imagination.corp-partner.google.com>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3934727
Reviewed-by: Aashish Sharma <shraash@google.com>
Reviewed-by: Guenter Roeck <groeck@chromium.org>
Commit-Queue: Guenter Roeck <groeck@chromium.org>
Tested-by: Aashish Sharma <shraash@google.com>
(cherry picked from commit 3f002c5fb5d87fc19e705e8e86545291507c33a8)
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3941152
Tested-by: Guenter Roeck <groeck@chromium.org>
Commit-Queue: Aashish Sharma <shraash@google.com>