FIXUP: CHROMIUM: media: mtk-vcodec: compute P/B0/B1 reflists in-driver
0-day reports:

drivers/media/platform/mtk-vcodec/vdec/vdec_h264_req_if.c:466:18: error:
	variable 'dpb_fields' set but not used [-Werror=unused-but-set-variable]

Remove the unused variable and the code setting it.

BUG=b:149437087
TEST=ARC++ Youtube playback is correct.

Change-Id: I76ddd8528933c1f4d9b566eed1a359a695f18a05
Disallow-Recycled-Builds: test-failures
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/2782360
Reviewed-by: Alexandre Courbot <acourbot@chromium.org>