FIXUP: FROMLIST: PM / AVS: SVS: Introduce SVS engine (take 2)
Builds still fail if THERMAL=m and MTK_SVS=y.

drivers/power/avs/mtk_svs.o: In function `svs_set_volts':
mtk_svs.c:(.text+0x1310): undefined reference to `thermal_zone_get_zone_by_name'
mtk_svs.c:(.text+0x131c): undefined reference to `thermal_zone_get_temp'
drivers/power/avs/mtk_svs.o: In function `svs_status_proc_show':
mtk_svs.c:(.text+0x2e48): undefined reference to `thermal_zone_get_zone_by_name'
mtk_svs.c:(.text+0x2e54): undefined reference to `thermal_zone_get_temp'

The previously set condition does not work. Try again.

BUG=b:131870177
TEST=make ARCH=arm64 allmodconfig

Change-Id: I914e0ec1bf2bc2e6ac167ab92bee4f7cf770bc4c
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/1817654
Commit-Queue: Fei Shao <fshao@chromium.org>
Reviewed-by: Fei Shao <fshao@chromium.org>