FIXUP: UPSTREAM: power: supply: Add Spreadtrum SC27XX fuel gauge unit driver
Well, not really a FIXUP. Using for reference. Mark the driver as BROKEN.
It doesn't compile. The first build error is:

drivers/power/supply/sc27xx_fuel_gauge.c:
	In function 'sc27xx_fgu_get_boot_capacity':
drivers/power/supply/sc27xx_fuel_gauge.c:137:9: error:
	implicit declaration of function 'power_supply_ocv2cap_simple'

There is no such function in chromeos-4.19. There are many similar errors
due to other undefined symbols.

BUG=chromium:957136
TEST=kernel really compiles

Change-Id: I65143c2073fdeeda25eedd138cc24bf0da81882f
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1586155
Reviewed-by: Simon Glass <sjg@chromium.org>
Reviewed-by: Nick Crews <ncrews@chromium.org>