FIXUP: CHROMIUM: mm: remove kstaled pmd page list walk
Architecture dependencies must only be removed if they don't exist.
This is not the case here, as the various build errors reported by
0-day clearly show.

include/linux/compiler.h:247:20: error: lvalue required as unary '&' operand
include/linux/compiler.h:253:22: note: in expansion of macro '__READ_ONCE'
include/linux/kernel.h:811:25: note: in expansion of macro '__no_side_effects'
include/linux/mm.h:1817:17: error: implicit declaration of function 'pte_offset_map'; did you mean 'pte_offset_map_lock'? [-Werror=implicit-function-declaration]
include/linux/mm.h:1817:17: warning: initialization makes pointer from integer without a cast [-Wint-conversion]
include/linux/mm.h:1825:2: error: implicit declaration of function 'pte_unmap'; did you mean 'memunmap'? [-Werror=implicit-function-declaration]
mm/kstaled.c:1199:55: error: dereferencing pointer to incomplete type 'struct page_vma_mapped_walk'
mm/kstaled.c:1227:3: error: implicit declaration of function 'page_vma_mapped_walk_done' [-Werror=implicit-function-declaration]
mm/kstaled.c:1242:7: error: implicit declaration of function 'pte_young'; did you mean 'page_count'? [-Werror=implicit-function-declaration]
mm/kstaled.c:1245:26: error: 'PMD_MASK' undeclared (first use in this function); did you mean 'P4D_MASK'?
mm/kstaled.c:1246:16: error: 'PMD_SIZE' undeclared (first use in this function); did you mean 'PUD_SIZE'?
mm/kstaled.c:1248:8: note: in expansion of macro 'min'
mm/kstaled.c:335:12: error: implicit declaration of function 'pmd_trans_huge'; did you mean 'pmd_trans_huge_lock'? [-Werror=implicit-function-declaration]
mm/kstaled.c:335:2: note: in expansion of macro 'VM_BUG_ON'
mm/kstaled.c:396:43: error: implicit declaration of function 'pte_pfn'; did you mean 'pte_val'? [-Werror=implicit-function-declaration]
mm/kstaled.c:396:8: error: implicit declaration of function 'pte_present'; did you mean 'pud_present'? [-Werror=implicit-function-declaration]
mm/kstaled.c:399:8: error: implicit declaration of function 'ptep_test_and_clear_young'; did you mean '__test_and_clear_bit'? [-Werror=implicit-function-declaration]
mm/kstaled.c:402:24: error: implicit declaration of function 'pte_page'; did you mean 'put_page'? [-Werror=implicit-function-declaration]
mm/kstaled.c:402:24: warning: passing argument 1 of 'compound_head' makes pointer from integer without a cast [-Wint-conversion]
mm/kstaled.c:424:8: note: in expansion of macro 'pte_offset_map_lock'
mm/kstaled.c:426:2: note: in expansion of macro 'pte_unmap_unlock'
mm/kstaled.c:445:41: error: implicit declaration of function 'pmd_addr_end'; did you mean 'p4d_addr_end'? [-Werror=implicit-function-declaration]
mm/kstaled.c:456:8: error: implicit declaration of function 'pmdp_test_and_clear_young'; did you mean 'cpumask_test_and_clear_cpu'? [-Werror=implicit-function-declaration]
mm/kstaled.c:462:10: error: implicit declaration of function 'pmd_page'; did you mean 'p4d_page'? [-Werror=implicit-function-declaration]
mm/kstaled.c:462:8: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
mm/kstaled.c:489:18: error: 'FIRST_USER_ADDRESS' undeclared (first use in this function)
mm/kstaled.c:516:3: error: implicit declaration of function 'mmput_async'; did you mean 'mmdrop_async'? [-Werror=implicit-function-declaration]
mm/kstaled.c:553:4: error: implicit declaration of function 'prefetchw' [-Werror=implicit-function-declaration]
mm/kstaled.c:632:7: note: in expansion of macro 'READ_ONCE'
mm/kstaled.c:820:35: error: 'struct zone' has no member named 'compact_defer_shift'
mm/kstaled.c:823:11: note: in expansion of macro 'max'
mm/kstaled.c:823:26: error: 'struct zone' has no member named 'compact_order_failed'

BUG=b:123039911
TEST=Test builds

Change-Id: If5e9f1cc4dc96af27f3ae8d072865024d26bef39
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/1946724
Reviewed-by: Yu Zhao <yuzhao@chromium.org>
(cherry picked from commit f7cc6bd641f2b16cb877842a7d0ec5b42d989dea)
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/1960665