Revert "CHROMIUM: drm/i915: Disable bitwise-instead-of-logical"
This reverts commit 37529f20bbee2a844642c7ac99a4d6d16eb38f4c.

Reason for revert: The warning is fixed in https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3446260.

Original change's description:
> CHROMIUM: drm/i915: Disable bitwise-instead-of-logical
>
> Suppress the clang warning bitwise-instead-of-logical which causes the
> following error with the new compiler:
>
> drivers/gpu/drm/i915/i915_drv.h:3235:9: error: use of bitwise '|' with
>  boolean operands [-Werror,-Wbitwise-instead-of-logical]
>          return i915_reset_backoff(error) | i915_terminally_wedged(error);
>
> The bug is harmless and wasn't fixed in 4.19 stable.
>
> BUG=b:208851882
> TEST=emerge-chell sys-kernel/chromeos-kernel-4_19 with llvm-next
>
> Change-Id: I6084b09bdeadda8a52abafbe960ee353601a896c
> Signed-off-by: Denis Nikitin <denik@google.com>
> Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3428006
> Reviewed-by: Ryan Beltran <ryanbeltran@chromium.org>
> Tested-by: Denis Nikitin <denik@chromium.org>
> Reviewed-by: Stéphane Marchesin <marcheu@chromium.org>
> Commit-Queue: Denis Nikitin <denik@chromium.org>

Bug: b:208851882
Change-Id: Ibdd377228440fcf6b83f6515aae839e0531ae943
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3456892
Reviewed-by: Ryan Beltran <ryanbeltran@chromium.org>
Reviewed-by: Guenter Roeck <groeck@chromium.org>
Tested-by: Denis Nikitin <denik@chromium.org>
Commit-Queue: Denis Nikitin <denik@chromium.org>