FIXUP: BACKPORT: FROMLIST: audit: collect audit task parameters
The offending commit moved declarations for audit_get_loginuid() and
audit_get_sessionid() from #ifdef CONFIG_AUDITSYSCALL to #ifdef
CONFIG_AUDIT. With CONFIG__AUDIT=y, CONFIG_AUDITSYSCALL=n, this
results in

In file included from init/init_task.c:12:0:
./include/linux/audit.h:557:22: error: redefinition of 'audit_get_loginuid'
 static inline kuid_t audit_get_loginuid(struct task_struct *tsk)
                      ^~~~~~~~~~~~~~~~~~
./include/linux/audit.h:179:22: note: previous definition of 'audit_get_loginuid' was here
 static inline kuid_t audit_get_loginuid(struct task_struct *tsk)
                      ^~~~~~~~~~~~~~~~~~
./include/linux/audit.h:561:28: error: redefinition of 'audit_get_sessionid'
 static inline unsigned int audit_get_sessionid(struct task_struct *tsk)
                            ^~~~~~~~~~~~~~~~~~~
./include/linux/audit.h:186:28: note: previous definition of 'audit_get_sessionid' was here
 static inline unsigned int audit_get_sessionid(struct task_struct *tsk)
                            ^~~~~~~~~~~~~~~~~~~

because the associated dummy functions were not moved.

BUG=b/131183634
TEST=Build with CONFIG_AUDIT=y, CONFIG_AUDITSYSCALL=n

Change-Id: I0cf43ffbcecb58794e0833655c4540b4d10932a6
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/1678820