UPSTREAM: soc: qcom: smsm: Add select IRQ_DOMAIN
Since we are using irq_domain_add_linear(), add a select on IRQ_DOMAIN.
This is needed in order to be able to remove the depends on ARCH_QCOM.

drivers/soc/qcom/smsm.c: In function smsm_inbound_entry:
drivers/soc/qcom/smsm.c:411:18: error: implicit declaration of function
  irq_domain_add_linear
  entry->domain = irq_domain_add_linear(node, 32, &smsm_irq_ops, entry);
                  ^~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Niklas Cassel <niklas.cassel@linaro.org>
Reviewed-by: Vivek Gautam <vivek.gautam@codeaurora.org>
Reviewed-by: Vinod Koul <vkoul@kernel.org>
Signed-off-by: Andy Gross <andy.gross@linaro.org>
(cherry picked from commit 0a5cdb4138f534bf58065acfb33d10336d6508df)

BUG=none
TEST=build for cheza

Change-Id: I25a8b61ac6a0bbb2ad0c3975c8f5d9ac1b158053
Signed-off-by: Matthias Kaehlcke <mka@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1309148
Reviewed-by: Evan Green <evgreen@chromium.org>