FIXUP: CHROMIUM: drm/vgem: fix cache synchronization on arm/arm64 (take three)
After trying to fix

ERROR: "arch_sync_dma_for_device" [drivers/gpu/drm/vgem/vgem.ko] undefined!

by restricting DRM and DRM_VGEM to bool, 0-day now reports:

drivers/gpu/drm/drm_dp_helper.o: In function `drm_dp_aux_register':
drm_dp_helper.c:(.text+0x29f2): undefined reference to `i2c_add_adapter'

and many similar errors.

It turns out that DRM uses many other subsystems which can be built
as module, so it can not be made bool. Since DRM_VGEM depends on DRM,
it can not be made bool either. Limit DRM_VGEM support to supported
configurations.

BUG=chromium:983368
TEST=Test builds

Signed-off-by: Guenter Roeck <groeck@chromium.org>
Change-Id: I5c4b35bdd87eaef5bc937d990abb1cb38f1b8e21
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/1800515
Reviewed-by: Douglas Anderson <dianders@chromium.org>
Reviewed-by: Rob Clark <robdclark@google.com>