CHROMIUM: thermal: mtk driver depends on CPU_FREQ and must be built into kernel
Building mtk-thermal driver as a module with the forward-ported SVS
driver causes a compile failure due to the redefinition of __inittest
due to the expansion of the late_initcall macro:
drivers/thermal/mtk_thermal.c:2071:1: error: redefinition of '__inittest'
module_platform_driver(mtk_thermal_driver);
^
include/linux/platform_device.h:231:2: note: expanded from macro 'module_platform_driver'
        module_driver(__platform_driver, platform_driver_register, \
        ^
include/linux/device.h:1621:3: note: expanded from macro 'module_driver'
} \
  ^
include/linux/module.h:131:42: note: expanded from macro '\
module_init'
        static inline initcall_t __maybe_unused __inittest(void)                \
                                                ^
drivers/thermal/mtk_thermal.c:1731:1: note: previous definition is here
late_initcall(mtk_svs_late_init);
^
include/linux/module.h:123:28: note: expanded from macro 'late_initcall'
                                        ^
include/linux/module.h:131:42: note: expanded from macro 'module_init'
        static inline initcall_t __maybe_unused __inittest(void)                \
                                                ^
drivers/thermal/mtk_thermal.c:2071:1: error: redefinition of 'init_module'
module_platform_driver(mtk_thermal_driver);
^
include/linux/platform_device.h:231:2: note: expanded from macro 'module_platform_driver'
        module_driver(__platform_driver, platform_driver_register, \
        ^
include/linux/device.h:1621:3: note: expanded from macro 'module_driver'
} \
  ^
include/linux/module.h:133:6: note: expanded from macro '\
module_init'
        int init_module(void) __copy(initfn) __attribute__((alias(#initfn)));
            ^
drivers/thermal/mtk_thermal.c:1731:1: note: previous definition is here
late_initcall(mtk_svs_late_init);
^
include/linux/module.h:123:28: note: expanded from macro 'late_initcall'
                                        ^
include/linux/module.h:133:6: note: expanded from macro 'module_init'
        int init_module(void) __copy(initfn) __attribute__((alias(#initfn)));

Copy of commit 19174f248337f9a7dada6a71011526c3bcb9045a from
chromeos-3.18 branch.

BUG=b:144478073
TEST=`USE=buildtest emerge-amd64-generic chromeos-kernel-4_19`

Change-Id: I7d4ed7ed6408027cf685f05258de291db3ece0be
Signed-off-by: Anand K Mistry <amistry@google.com>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/2215661
Reviewed-by: Nicolas Boichat <drinkcat@chromium.org>
Commit-Queue: Anand Mistry <amistry@chromium.org>
Tested-by: Anand Mistry <amistry@chromium.org>