msm: mdss: Fix uninitialized `vysnc_time` variable usage
Clang warns:
drivers/video/fbdev/msm/mdss_mdp_intf_cmd.c:1381:28: error:
      variable 'vsync_time' is uninitialized when used here
      [-Werror,-Wuninitialized]
                        tmp->vsync_handler(ctl, vsync_time);
                                                ^~~~~~~~~~
drivers/video/fbdev/msm/mdss_mdp_intf_cmd.c:1367:2: note: variable
      'vsync_time' is declared here
        ktime_t vsync_time;
        ^
1 error generated.

Signed-off-by: Tashfin Shakeer Rhythm <tashfinshakeerrhythm@gmail.com>