FIXUP: FROMLIST: OPP: Add function to look up required OPP's for a given OPP
dev_pm_opp_xlate_opp() can be called from code not built into the kernel
and thus must be exported.

This fixes the following error, seen if devfreq/governor_passive is built
as module.

ERROR: "dev_pm_opp_xlate_opp" [drivers/devfreq/governor_passive.ko] undefined!

BUG=b:122571050
TEST=Call dev_pm_opp_xlate_opp module

Change-Id: Id98283a84de05fa4f8ef5e8447efebe53cfb477d
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/1718349
Commit-Queue: Hsin-Yi Wang <hsinyi@chromium.org>
Reviewed-by: Hsin-Yi Wang <hsinyi@chromium.org>