xiaomi: fpc: Map `name` string to `fpc_rails_t` enum
This introduces a function to map the "name" string to its corresponding
fpc_rails_t enumeration value. name_to_fpc_rail() compares the provided
name string with the values from the "vreg_conf" array and returns the
respective enumerators.
In regulator_enable_store(), the name obtained from the input buffer is
passed through name_to_fpc_rail() to convert it to the corresponding
fpc_rails_t value.

This fixes the following compilation error:

../drivers/input/fingerprint/fpc/fpc1020_platform_tee.c:257:27: error: incompatible pointer to integer conversion passing 'char[16]' to parameter of type 'fpc_rails_t' [-Wint-conversion]
        rc = vreg_setup(fpc1020, name, enable);
                                 ^~~~
../drivers/input/fingerprint/fpc/fpc1020_platform_tee.c:113:72: note: passing argument to parameter 'fpc_rail' here
static inline int vreg_setup(struct fpc1020_data *fpc1020, fpc_rails_t fpc_rail,
                                                                       ^

Fixes: 464ebdf0e3e1 ("xiaomi: fpc: Fix and optimize regulators handling")
Signed-off-by: Tashfin Shakeer Rhythm <tashfinshakeerrhythm@gmail.com>