FIXUP: CHROMIUM: ARM: rockchip: pm: Support deep suspend
gcc complains when building arm:allmodconfig:

Error: selected processor does not support `isb' in ARM mode

Use isb() instead of direct assembler code.

BUG=chromium:941638
TEST=suspend_stress_test

Change-Id: I3349ccc1382a92215a724645bd4c72000dd97879
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1575359
Reviewed-by: Douglas Anderson <dianders@chromium.org>