UPSTREAM: media: mtk-mdp: Correct return type for mem2mem buffer helpers
Fix the assigned type of mem2mem buffer handling API.
Namely, these functions:

 v4l2_m2m_next_buf
 v4l2_m2m_last_buf
 v4l2_m2m_buf_remove
 v4l2_m2m_next_src_buf
 v4l2_m2m_next_dst_buf
 v4l2_m2m_last_src_buf
 v4l2_m2m_last_dst_buf
 v4l2_m2m_src_buf_remove
 v4l2_m2m_dst_buf_remove

return a struct vb2_v4l2_buffer, and not a struct vb2_buffer.

Fixing this is necessary to fix the mem2mem buffer handling API,
changing the return to the correct struct vb2_v4l2_buffer instead
of a void pointer.

Signed-off-by: Ezequiel Garcia <ezequiel@collabora.com>
Signed-off-by: Hans Verkuil <hverkuil-cisco@xs4all.nl>
Signed-off-by: Mauro Carvalho Chehab <mchehab+samsung@kernel.org>
(cherry picked from commit 9af469c5be3b031e651ca90ea193f09bae0792d3)

This patch is necessary to fix up commit 2e8d362eed450 ("UPSTREAM: media:
v4l2-mem2mem: Correct return type for mem2mem buffer helpers" and to avoid
the following build error.

drivers/media/platform/mtk-mdp/mtk_mdp_m2m.c:
	In function 'mtk_mdp_m2m_get_bufs':
drivers/media/platform/mtk-mdp/mtk_mdp_m2m.c:482:9: error:
	assignment from incompatible pointer type

BUG=chromium:965375
TEST=emerge-veyron_minnie-kernelnext chromeos-kernel-4_19

Change-Id: I6a280b1d4bbe08d6fb5fb8f3d38b014de24727e0
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/1683896
Reviewed-by: Sean Paul <seanpaul@chromium.org>
Reviewed-by: Alexandre Courbot <acourbot@chromium.org>
Commit-Queue: Alexandre Courbot <acourbot@chromium.org>