FIXUP: CHROMIUM: platform/chrome: pd_update: Use usbpd notifier
0-day reports:

ld: drivers/platform/chrome/cros_ec_pd_update.o:
	in function `plat_cros_ec_pd_remove':
>> drivers/platform/chrome/cros_ec_pd_update.c:885:
	undefined reference to `cros_usbpd_unregister_notify'
ld: drivers/platform/chrome/cros_ec_pd_update.o:
	in function `plat_cros_ec_pd_probe':
>> drivers/platform/chrome/cros_ec_pd_update.c:872:
	undefined reference to `cros_usbpd_register_notify'

Add the missing dependency.

BUG=chromium:965213
TEST=Buildtest

Change-Id: I713ed7156e8c12bf4c51421d581cc07eda307d0b
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/2082903
Reviewed-by: Benson Leung <bleung@google.com>
Reviewed-by: Prashant Malani <pmalani@chromium.org>